from enum import Enum


class AutomationState(str, Enum):
    
    STARTING = "STARTING"
    OPENING_BROWSER = "OPENING_BROWSER"
    OPENING_JOB = "OPENING_JOB"
    CLICKING_APPLY = "CLICKING_APPLY"
    WAITING_LOGIN = "WAITING_LOGIN"
    WAITING_CAPTCHA = "WAITING_CAPTCHA"
    FILLING_FORM = "FILLING_FORM"
    NAVIGATING = "NAVIGATING"
    SUBMITTING = "SUBMITTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"