from enum import Enum


class AutomationState(str, Enum):
    
    STARTING = "STARTING"
    OPENING_BROWSER = "OPENING_BROWSER"
    OPENING_JOB = "OPENING_JOB"
    FINDING_APPLY = "FINDING_APPLY"
    APPLY_CLICKED = "APPLY_CLICKED"
    SCANNING_FORM = "SCANNING_FORM"
    FILLING_FORM = "FILLING_FORM"
    UPLOADING_RESUME = "UPLOADING_RESUME"
    CLICKING_NEXT = "CLICKING_NEXT"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    CAPTCHA_REQUIRED = "CAPTCHA_REQUIRED"
    USER_INPUT_REQUIRED = "USER_INPUT_REQUIRED"
    SUBMITTING = "SUBMITTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"